create table public.blogs (
  id uuid not null default gen_random_uuid (),
  title text not null,
  slug text not null,
  excerpt text null,
  content text null,
  image_url text null,
  tags text[] null default '{}'::text[],
  faqs jsonb null default '[]'::jsonb,
  is_featured boolean null default false,
  is_published boolean null default true,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  category_id uuid null,
  meta_title text null,
  meta_description text null,
  keywords text[] null,
  robots text null default 'index, follow'::text,
  canonical_url text null,
  og_title text null,
  og_description text null,
  og_image_url text null,
  author_id text null,
  enable_structured_data boolean null default true,
  constraint blogs_pkey primary key (id),
  constraint blogs_slug_key unique (slug),
  constraint blogs_author_id_fkey foreign KEY (author_id) references profiles (id),
  constraint blogs_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;